/**********************************************************************
  Filename    : Sketch_02.3_Motor_Encoder
  Description : Use Raspberry Pi Pico Gets the coded value generated by
                motor rotation
  Auther      : www.freenove.com
  Modification: 2024/08/23
**********************************************************************/
const int encoderA1Pin = 6;// Encoder1 A pin
const int encoderB1Pin = 7;// Encoder1 B pin

int encoder1Pos = 0,lastEncoded1 = 0,encoder1;

void Getencoder()
{
  int MSB1 = digitalRead(encoderA1Pin);
  int LSB1 = digitalRead(encoderB1Pin);

  int encoded1 = (MSB1 << 1) | LSB1;
  int sum1 = (lastEncoded1 << 2) | encoded1;

  // Determine the motor rotation direction
  if (sum1 == 0b1101 || sum1 == 0b0100 || sum1 == 0b0010 || sum1 == 0b1011) encoder1Pos++;
  if (sum1 == 0b1110 || sum1 == 0b0111 || sum1 == 0b0001 || sum1 == 0b1000) encoder1Pos--;

  lastEncoded1 = encoded1;
}

void setup() {
  // put your setup code here, to run once:
  // Set the serial port baud rate to 115200
  Serial.begin(115200);
  // Enable encoder pin to input mode
  pinMode(encoderA1Pin,INPUT);
  pinMode(encoderB1Pin,INPUT);
  // Enter interrupt when level reverses
  attachInterrupt(digitalPinToInterrupt(encoderA1Pin), Getencoder, CHANGE);
  attachInterrupt(digitalPinToInterrupt(encoderB1Pin), Getencoder, CHANGE);
}

void loop() {
  // put your main code here, to run repeatedly:
  // The encoder's value is printed every 3 seconds
  Serial.print("Encoder:");
  Serial.println(encoder1Pos);
  encoder1Pos = 0;
  delay(3000);
}
